version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  db:
    build: ./db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
    volumes:
       - mongodb_data:/data/db
  
  volumes:
    mongodb_data:
      driver: local